import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Providers from '@/components/Providers'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/svg+xml" href="/assests/images/rocket.svg" />
      <title>Todo App</title>
      </head>
      <body
        className="bg-[rgba(26,26,26,1)] flex flex-col items-center"
      >
        <Header />
      

        <Providers>
          <div className="lg:w-[736px] w-full lg:px-0 px-12">
          {children}
          </div>
          
        </Providers>

      </body>
    </html>
  );
}
